import { mkdir, writeFile, readFile, readdir } from 'node:fs/promises'
import path from 'node:path'
import { publishWorkflow, releaseScripts } from './workflows.ts'

/** Files to write, keyed by path relative to the target directory. */
export type Files = Record<string, string>

const json = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`

/** Versions the generated projects pin, kept beside the ones this package uses. */
export const VERSIONS = {
  monolith: '^0.1.0-alpha.0',
  // Provides `fg-dist`, which the release scripts and the publish workflow call.
  distribution: '^0.1.0-alpha.0',
  // Provides `fg-policy`, which `fg-dist policy` calls to build the organization's policy.
  policy: '^0.1.0-alpha.0',
  next: '^16.3.5',
  react: '^19.3.0',
  types: {
    node: '^26.6.2',
    react: '^19.3.0',
    reactDom: '^19.3.0',
  },
  eslint: '^9.39.5',
  eslintConfigNext: '^16.3.5',
  portless: '^0.15.6',
  typescript: '^6.0.3',
  // Exact, because this is what `packageManager` means. The publish workflow's
  // pnpm comes from it, so a module without one cannot build in CI.
  pnpm: 'pnpm@10.28.0',
} as const

const GITIGNORE = `node_modules
.next
.turbo
out
build
next-env.d.ts
*.tsbuildinfo

# derived mount points; the symlinks under src/ are what is committed
/app/
/pages/

# generated by next dev
AGENTS.md
CLAUDE.md
`

const TSCONFIG = {
  compilerOptions: {
    target: 'ES2017',
    lib: ['dom', 'dom.iterable', 'esnext'],
    allowJs: true,
    skipLibCheck: true,
    strict: true,
    noEmit: true,
    esModuleInterop: true,
    module: 'esnext',
    moduleResolution: 'bundler',
    resolveJsonModule: true,
    isolatedModules: true,
    jsx: 'preserve',
    incremental: true,
    plugins: [{ name: 'next' }],
  },
  include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
  exclude: ['node_modules'],
}

/**
 * A repository that composes modules.
 *
 * The monolith app lives at `apps/monolith` so modules can be added beside it
 * as `apps/<name>`, which is where `add-module` puts them.
 */
export const monolithRepo = (name: string, origin?: string): Files => ({
  '.gitignore': `node_modules\n.turbo\n`,
  // Modules are linked through the workspace, so nothing here carries a
  // version: the submodule commit is the pin and its package.json is the
  // version. Keeping the workspace protocol stops pnpm writing one back in.
  '.npmrc': `link-workspace-packages=true\nsave-workspace-protocol=true\n`,
  'pnpm-workspace.yaml': `packages:\n  - "apps/*"\n  - "packages/*"\n  - "packages/*/docs"\n`,
  'package.json': json({
    name,
    version: '0.1.0-alpha.0',
    private: true,
    ...(origin ? { repository: { type: 'git', url: origin } } : {}),
    scripts: {
      build: 'turbo run build',
      // The monolith already serves every mounted app, so running their dev
      // servers as well would be the same routes twice.
      dev: "turbo run dev --filter=./apps/monolith --filter='./packages/*'",
      // Each app on its own instead, for working on one in isolation or on
      // anything the monolith cannot serve from one deployment.
      'dev-services': 'turbo run dev:service',
      lint: 'turbo run lint',
    },
    devDependencies: { turbo: '^2.11.2' },
  }),
  'turbo.json': json({
    $schema: 'https://turbo.build/schema.json',
    tasks: {
      build: { dependsOn: ['^build'], outputs: ['.next/**', '!.next/cache/**', 'dist/**'] },
      lint: { dependsOn: ['^lint'] },
      dev: { persistent: true, cache: false },
      'dev:service': { persistent: true, cache: false },
    },
  }),
  'apps/monolith/package.json': json({
    name: `${name}-monolith`,
    version: '0.1.0-alpha.0',
    private: true,
    scripts: {
      // Each takes a copy of the organization's policy to run, when there is one.
      dev: 'fg-dist policy use && next dev',
      build: 'fg-dist policy use && next build',
      start: 'next start',
      lint: 'eslint',
    },
    dependencies: {
      '@fairgarden/monolith': VERSIONS.monolith,
      next: VERSIONS.next,
      react: VERSIONS.react,
      'react-dom': VERSIONS.react,
    },
    devDependencies: {
      '@fairgarden/distribution': VERSIONS.distribution,
      '@types/node': VERSIONS.types.node,
      '@types/react': VERSIONS.types.react,
      '@types/react-dom': VERSIONS.types.reactDom,
      eslint: VERSIONS.eslint,
      'eslint-config-next': VERSIONS.eslintConfigNext,
      typescript: VERSIONS.typescript,
    },
  }),
  'apps/monolith/next.config.ts': `import { withMonolith } from '@fairgarden/monolith'

export default withMonolith(
  {
    // the monolith's own Next config
  },
  {
    // mount name -> module, added by \`fg-dist add-module\`
  }
)
`,
  'apps/monolith/tsconfig.json': json(TSCONFIG),
  'apps/monolith/eslint.config.mjs': `import next from 'eslint-config-next/core-web-vitals'

/** @type {import('eslint').Linter.Config[]} */
const config = [{ ignores: ['node_modules/**', '.next/**', 'app/**', 'pages/**'] }, ...next]

export default config
`,
  'apps/monolith/.gitignore': GITIGNORE,
  'apps/monolith/src/app/layout.tsx': `export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`,
  'apps/monolith/src/app/page.tsx': `export default function Home() {
  return <main>Nothing mounted yet. Add a module with \`fg-dist add-module\`.</main>
}
`,
})

/**
 * A repository that can be mounted into a monolith.
 *
 * It is an ordinary Next app; the only additions are the portability check and
 * the lint rules that keep it mountable.
 */
/** `@acme/widget` -> `widget`, which is what a hostname wants. */
const unscoped = (packageName: string): string =>
  packageName.replace(/^@[^/]+\//, '')

export const moduleRepo = (packageName: string, origin?: string): Files => ({
  // A module releases on its own schedule, so it carries its own workflow.
  ...publishWorkflow(packageName),
  '.gitignore': `node_modules\n.next\n.turbo\nnext-env.d.ts\n*.tsbuildinfo\n\n# generated by next dev\nAGENTS.md\nCLAUDE.md\n`,
  'package.json': json({
    name: packageName,
    version: '0.1.0-alpha.0',
    // Not private: a module publishes itself, so that a monolith which cannot
    // reach it as a submodule can install it as a package instead. Scoped
    // packages publish restricted by default; say so rather than leave it to
    // whoever reads this to remember.
    publishConfig: { access: 'restricted' },
    // What CI installs with — see .github/actions/publish-prepare.
    packageManager: VERSIONS.pnpm,
    // A module is consumed as source — its routes are read out of the package —
    // so the tarball carries the source rather than a build.
    files: ['app', 'lib', 'pages', 'public', 'next.config.ts'],
    // A monolith adds this repository as a submodule, so record where it lives.
    ...(origin ? { repository: { type: 'git', url: origin } } : {}),
    scripts: {
      dev: 'next dev',
      // Served at a stable hostname instead of a port, so several apps can run
      // at once without colliding: https://${unscoped(packageName)}.localhost
      'dev:service': `portless ${unscoped(packageName)} next dev`,
      build: 'next build',
      start: 'next start',
      lint: 'eslint',
      // Called by .github/workflows/publish.yml, and by you — see the readme.
      ...releaseScripts(packageName),
    },
    dependencies: {
      next: VERSIONS.next,
      react: VERSIONS.react,
      'react-dom': VERSIONS.react,
    },
    devDependencies: {
      '@fairgarden/distribution': VERSIONS.distribution,
      '@fairgarden/monolith': VERSIONS.monolith,
      '@types/node': VERSIONS.types.node,
      '@types/react': VERSIONS.types.react,
      '@types/react-dom': VERSIONS.types.reactDom,
      eslint: VERSIONS.eslint,
      'eslint-config-next': VERSIONS.eslintConfigNext,
      // `dev:service` serves this at a stable hostname instead of a port.
      portless: VERSIONS.portless,
      typescript: VERSIONS.typescript,
    },
  }),
  'next.config.ts': `import type { NextConfig } from 'next'
import { withMonolithicPortability } from '@fairgarden/monolith'

const nextConfig: NextConfig = {}

// Reports anything that would not survive being mounted in a monolith.
export default withMonolithicPortability(nextConfig)
`,
  'tsconfig.json': json({
    ...TSCONFIG,
    compilerOptions: {
      ...TSCONFIG.compilerOptions,
      // So this module's own files can import each other by package name,
      // which is what keeps them resolvable once mounted.
      paths: { [`${packageName}/*`]: ['./*'] },
    },
  }),
  'eslint.config.mjs': `import next from 'eslint-config-next/core-web-vitals'
import monolith from '@fairgarden/monolith/eslint'

/** @type {import('eslint').Linter.Config[]} */
const config = [
  { ignores: ['node_modules/**', '.next/**'] },
  ...next,
  ...monolith.configs.recommended,
]

export default config
`,
  'lib/link.ts': `import { createHref, createLink } from '@fairgarden/monolith/link'

// Use these instead of next/link so hrefs carry the mount point when this
// module is served inside a monolith.
export const Link = createLink('${packageName}')
export const href = createHref('${packageName}')
`,
  'app/layout.tsx': `export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`,
  'app/page.tsx': `import { Link } from '${packageName}/lib/link'

export default function Home() {
  return (
    <main>
      <h1>${packageName}</h1>
      <Link href="/">Home</Link>
    </main>
  )
}
`,
})

/** Write a file map, creating directories as needed. */
export const write = async (root: string, files: Files): Promise<string[]> => {
  const written: string[] = []

  for (const [relative, contents] of Object.entries(files)) {
    const full = path.join(root, relative)
    await mkdir(path.dirname(full), { recursive: true })
    await writeFile(full, contents)
    written.push(relative)
  }

  return written.sort()
}

/** Whether a directory has anything in it, so `init` never writes over work. */
export const isEmpty = async (dir: string): Promise<boolean> => {
  const entries = await readdir(dir).catch(() => undefined)
  if (!entries) return true
  return entries.filter((entry) => entry !== '.git').length === 0
}

export const readPackageName = async (root: string): Promise<string | undefined> => {
  try {
    const pkg = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'))
    return typeof pkg.name === 'string' ? pkg.name : undefined
  } catch {
    return undefined
  }
}

/** `2024.01.15` — the date-based version a distribution is released under. */
export const calendarVersion = (on: Date = new Date()): string =>
  [
    on.getUTCFullYear(),
    String(on.getUTCMonth() + 1).padStart(2, '0'),
    String(on.getUTCDate()).padStart(2, '0'),
  ].join('.')

/**
 * The organization's `policies/`: its `.manifest`, and a workspace package
 * that builds and tests it with `fg-dist policy`. Empty of rules: until the
 * organization writes some, the modules' own decide.
 */
const policiesFiles = (name: string, origin?: string): Files => ({
  'policies/.manifest': json({
    metadata: {
      organization: name,
      ...(origin ? { source: origin.replace(/\.git$/, '') } : {}),
    },
  }),
  'policies/package.json': json({
    name: `${name}-policies`,
    private: true,
    type: 'module',
    scripts: { build: 'fg-dist policy build', test: 'fg-dist policy test' },
    devDependencies: {
      '@fairgarden/distribution': VERSIONS.distribution,
      '@fairgarden/policy': VERSIONS.policy,
    },
  }),
  'policies/.gitignore': '/dist\n/node_modules\n',
  'policies/Readme.md': `# Policies

The organization's rules for the services this distribution ships: who may
join, what is shared and with whom. Each module brings its own rules, in its
own \`policies/\`; the organization's go here, in the same Rego packages,
adding to the places those rules leave for them — so upgrading a module keeps
them.

Change them by pull request, like anything else here: what is merged is what
the next deployment runs, and anyone can read it on the id service's
\`/policy\` page.

\`\`\`bash
fg-dist policy test     # each module's tests, then these on top
fg-dist policy build    # what the services will run
\`\`\`

\`.manifest\` says whose rules these are; its \`metadata\` is shown with them.
`,
})

/**
 * A repository that ships a set of modules to end users.
 *
 * The root package.json is the distribution manifest: its version is the date
 * it was released, and its dependencies are the modules it ships, each at a
 * semver version. `extends` names another distribution whose modules this one
 * inherits and may move ahead of, but never behind.
 */
export const distributionRepo = (
  name: string,
  origin?: string,
  parent?: string,
  { monolith = true }: { monolith?: boolean } = {}
): Files => {
  // A distribution of only Next apps can deploy as one. A complex one cannot,
  // and then each app under apps/ is deployed on its own — which is fine for
  // an audience that already has deployment infrastructure.
  const files = monolith
    ? monolithRepo(name, origin)
    : {
        '.gitignore': `node_modules\n.turbo\n`,
        '.npmrc': `link-workspace-packages=true\nsave-workspace-protocol=true\n`,
        'pnpm-workspace.yaml': `packages:\n  - "apps/*"\n  - "packages/*"\n  - "packages/*/docs"\n`,
        'turbo.json': json({
          $schema: 'https://turbo.build/schema.json',
          tasks: {
            build: {
              dependsOn: ['^build'],
              outputs: ['.next/**', '!.next/cache/**', 'dist/**'],
            },
            lint: { dependsOn: ['^lint'] },
            dev: { persistent: true, cache: false },
          },
        }),
      }

  // The organization's policy, built on every module's own; a workspace
  // package, so turbo builds it once for every service that runs it.
  files['pnpm-workspace.yaml'] = files['pnpm-workspace.yaml'].replace(
    '  - "packages/*"\n',
    '  - "packages/*"\n  - "policies"\n'
  )
  Object.assign(files, policiesFiles(name, origin))

  files['package.json'] = json({
    name,
    // End users read a date, not a semver range: it says how old their copy is.
    version: calendarVersion(),
    private: true,
    ...(origin ? { repository: { type: 'git', url: origin } } : {}),
    ...(parent ? { distribution: { extends: parent } } : {}),
    scripts: {
      build: 'turbo run build',
      // With a monolith, running the mounted apps as well would serve the same
      // routes twice. Without one, every app is its own deployment and there
      // is nothing else to run them.
      dev: monolith
        ? "turbo run dev --filter=./apps/monolith --filter='./packages/*'"
        : 'turbo run dev:service',
      'dev-services': 'turbo run dev:service',
      lint: 'turbo run lint',
    },
    // Modules go here, each pinned to the semver version this ships.
    dependencies: parent ? { [parent]: 'latest' } : {},
    devDependencies: { turbo: '^2.11.2' },
  })

  files['Readme.md'] = `# ${name}

A distribution: the set of modules shipped together, released under a date-based
version so it is obvious how old a copy is.

Modules are listed in \`dependencies\`, each pinned to a semver version, and
checked out as submodules. Add one with \`fg-dist add-module <url>\`, and see
what has moved with \`fg-dist sync\`.

## Deploying
${
  monolith
    ? `
Every module is mounted into \`apps/monolith\`, which deploys as one Next app.
`
    : `
Each app under \`apps/\` is deployed on its own. There is no monolith app,
which is the right shape once the distribution is too complex to serve from one
deployment — and fine for an audience that already runs deployment
infrastructure.
`
}${
  parent
    ? `
## Extends

This distribution extends \`${parent}\`. It ships that distribution's modules
and may move ahead of them, but can never ship anything older. \`fg-dist check\`
fails when it does${monolith ? ', and so does the monolith build' : ''}.
`
    : ''
}`

  return files
}
